name: Build binaries

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        id: cache-1
        uses: actions/cache@v2
        with:
          path: cache
          key: ${{ runner.os }}-cache-1

      - name: Download devkitPPC r36, libogc 1.8.24, bin2s and elf2dol
        if: steps.cache-1.outputs.cache-hit != 'true'
        # general-tools is needed for bin2s and gamecube-tools is needed for elf2dol
        run: | 
          mkdir cache && cd cache
          wget "https://wii.leseratte10.de/devkitPro/file.php/devkitPPC-r39-2-linux_x86_64.pkg.tar.xz"
          wget "https://wii.leseratte10.de/devkitPro/file.php/devkitppc-rules-1.1.1-1-any.pkg.tar.xz"
          wget "https://wii.leseratte10.de/devkitPro/file.php/libogc-2.3.1-1-any.pkg.tar.xz"
          wget "https://wii.leseratte10.de/devkitPro/file.php/general-tools-1.2.0-2-linux_x86_64.pkg.tar.xz"
          wget "https://wii.leseratte10.de/devkitPro/file.php/gamecube-tools-1.0.3-1-linux_x86_64.pkg.tar.xz"
          cd ..

      - name: Extract devkitPPC r36, libogc 1.8.24, bin2s and elf2dol
        # general-tools is needed for bin2s and gamecube-tools is needed for elf2dol
        run: | 
          tar -xf cache/devkitPPC-r39-2-linux_x86_64.pkg.tar.xz opt/devkitpro/devkitPPC --strip-components=1
          tar -xf cache/devkitppc-rules-1.1.1-1-any.pkg.tar.xz opt/devkitpro/devkitPPC --strip-components=1
          tar -xf cache/libogc-2.3.1-1-any.pkg.tar.xz opt/devkitpro/libogc --strip-components=1
          tar -xf cache/general-tools-1.2.0-2-linux_x86_64.pkg.tar.xz opt/devkitpro/tools/bin/bin2s --strip-components=4
          sudo cp bin2s /usr/local/bin/bin2s
          tar -xf cache/gamecube-tools-1.0.3-1-linux_x86_64.pkg.tar.xz opt/devkitpro/tools/bin/elf2dol --strip-components=4
          sudo cp elf2dol /usr/local/bin/elf2dol

      - name: Compile
        run: |
          PATH=$(pwd)/devkitpro/devkitPPC/bin:$PATH DEVKITPPC=$(pwd)/devkitpro/devkitPPC DEVKITPRO=$(pwd)/devkitpro make
      - name: Package
        id: pack
        run: |
          cp -r wii/apps apps
          mkdir -p apps/wiiflow/
          cp -r out/bins apps/wiiflow/bins
          cp -r out/imgs apps/wiiflow/imgs
          cp out/boot.dol apps/wiiflow/
          mkdir -p wiiflow
          cp -r wii/wiiflow/Languages wiiflow/languages
          cp -r wii/wiiflow/themes_lite wiiflow/themes_lite
          echo "::set-output name=sha::$(echo ${GITHUB_SHA} | head -c 7)"

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with: 
          name: wiiflow_lite_${{ steps.pack.outputs.sha }}
          path: |
            apps
            wiiflow
